- hosts: all
  become: true
  become_user: don
  tasks:

#  - name: update repository index
#    apt:
#      update_cache: yes


  - name: create simone user
    user: 
      name: simone
      groups: root

  -  name: add sudoers file for simone
     copy:
       src: ~/ansible/files/sudoer_simone
       dest: /etc/sudoers.d/simone
       owner: root
       group: root
       mode: 0440